name: vmdm-paper-analysis
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - networkx
  - adjusttext
  - python-pptx
  - openpyxl
  - pip
